const API='https://myschool-ai-sjwz.onrender.com';
const app=document.getElementById('app');
const get=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch(e){return null}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const classes=['1-A','1-B','2-A','2-B','3-A','3-B','4-A','4-B','5-A','5-B','6-A','6-B','7-A','7-B','8-A','8-B','9-A','9-B','10-A','10-B','11-A','11-B'];
function welcome(){app.innerHTML='<div class="wrap"><section class="card center"><div class="logo">🏫</div><h1 class="title">Xush kelibsiz</h1><p class="muted">Maktab tizimiga xush kelibsiz!</p><button class="btn" onclick="login()">Kirish</button><button class="btn secondary" onclick="register()">Ro\'yxatdan o\'tish</button><button class="btn secondary" onclick="adminLogin()">Katta administrator</button></section></div>'}
function register(){app.innerHTML='<div class="wrap"><section class="card"><button class="back" onclick="welcome()">← Orqaga</button><h1 class="title">Ro\'yxatdan o\'tish</h1><p class="muted">Ma\'lumotlaringiz katta administrator tomonidan tekshiriladi.</p><form id="reg"><div class="field"><label>Ism</label><input id="firstName" required maxlength="60"></div><div class="field"><label>Familiya</label><input id="lastName" required maxlength="60"></div><div class="field"><label>Sinf</label><select id="className" required><option value="">Sinfni tanlang</option>'+classes.map(x=>'<option>'+x+'</option>').join('')+'</select></div><div class="field"><label>Maktab kodi (agar berilgan bo\'lsa)</label><input id="schoolCode" maxlength="40"></div><button class="btn">Ariza yuborish</button><div id="formMsg"></div></form></section></div>';document.getElementById('reg').onsubmit=submitRegistration}
async function submitRegistration(e){e.preventDefault();const msg=document.getElementById('formMsg');msg.textContent='Yuborilmoqda...';try{const r=await fetch(API+'/api/students/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firstName:firstName.value,lastName:lastName.value,className:className.value,schoolCode:schoolCode.value})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Xatolik');save('myschool_pending_application',d.applicationId);pending()}catch(x){msg.className='error';msg.textContent=x.message}}
function pending(){app.innerHTML='<div class="wrap"><section class="card center"><div class="logo">⏳</div><h1 class="title">Arizangiz qabul qilindi</h1><p class="muted">Ma\'lumotlaringiz katta administrator tomonidan tekshirilmoqda.</p><div id="pendingStatus" class="status">Arizangiz tekshirilmoqda...</div><button class="btn secondary" onclick="checkStatus()">Holatni tekshirish</button></section></div>';checkStatus();window.poll=setInterval(checkStatus,10000)}
async function checkStatus(){const id=get('myschool_pending_application');if(!id)return;try{const r=await fetch(API+'/api/students/status/'+encodeURIComponent(id));const d=await r.json();const box=document.getElementById('pendingStatus');if(!box)return;if(d.status==='approved'){clearInterval(window.poll);save('myschool_student',{studentId:d.studentId,firstName:d.firstName,lastName:d.lastName,className:d.className});localStorage.removeItem('myschool_pending_application');box.innerHTML='<div class="success"><b>Tasdiqlandi!</b><br>Student ID: <strong>'+esc(d.studentId)+'</strong></div>';setTimeout(home,1500)}else if(d.status==='rejected'){clearInterval(window.poll);box.innerHTML='<div class="error"><b>Ariza rad etildi.</b><br>'+esc(d.rejectionReason)+'</div>'}else box.textContent='Arizangiz hali tekshirilmoqda...'}catch(e){const box=document.getElementById('pendingStatus');if(box)box.textContent='Server bilan bog‘lanishda xatolik.'}}
function login(){app.innerHTML='<div class="wrap"><section class="card"><button class="back" onclick="welcome()">← Orqaga</button><h1 class="title">Kirish</h1><p class="muted">Student ID orqali kirish keyingi bosqichda ulanadi.</p></section></div>'}
function home(){const s=get('myschool_student');if(!s)return welcome();app.innerHTML='<div class="wrap"><section class="card center"><div class="logo">🎓</div><h1 class="title">MySchool</h1><p class="muted">'+esc(s.firstName)+' '+esc(s.lastName)+'<br>Sinf: '+esc(s.className)+'<br>Student ID: <b>'+esc(s.studentId)+'</b></p><p class="success">Tasdiqlash muvaffaqiyatli yakunlandi.</p></section></div>'}
function adminLogin(){app.innerHTML='<div class="wrap"><section class="card"><button class="back" onclick="welcome()">← Orqaga</button><h1 class="title">Katta administrator</h1><div class="field"><label>Login</label><input id="au"></div><div class="field"><label>Parol</label><input id="ap" type="password"></div><button class="btn" onclick="doAdminLogin()">Kirish</button><div id="adminMsg"></div></section></div>'}
async function doAdminLogin(){const msg=document.getElementById('adminMsg');try{const r=await fetch(API+'/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:au.value,password:ap.value})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Xatolik');save('myschool_admin_token',d.token);adminPanel()}catch(e){msg.className='error';msg.textContent=e.message}}
async function adminPanel(){const token=get('myschool_admin_token');if(!token)return adminLogin();app.innerHTML='<div class="wrap"><section class="card admin"><h1 class="title">Katta administrator</h1><p class="muted">🔔 Yangi o‘quvchi arizalari</p><div id="adminList">Yuklanmoqda...</div><button class="btn secondary" onclick="adminPanel()">Yangilash</button><button class="btn danger" onclick="localStorage.removeItem(\'myschool_admin_token\');welcome()">Chiqish</button></section></div>';try{const r=await fetch(API+'/api/admin/applications',{headers:{Authorization:'Bearer '+token}});if(r.status===401)throw new Error('Sessiya tugagan.');const d=await r.json(),list=document.getElementById('adminList');if(!d.items.length){list.innerHTML='<div class="status">Hozircha yangi ariza yo‘q.</div>';return}list.innerHTML=d.items.map(a=>'<article class="app-item"><span class="badge">Yangi ariza</span><h3>'+esc(a.firstName)+' '+esc(a.lastName)+'</h3><p class="muted">Sinf: <b>'+esc(a.className)+'</b><br>Maktab kodi: '+esc(a.schoolCode||'kiritilmagan')+'</p><div class="row"><button class="btn" onclick="approve(\''+a._id+'\')">Tasdiqlash</button><button class="btn danger" onclick="rejectApp(\''+a._id+'\')">Rad etish</button></div></article>').join('')}catch(e){document.getElementById('adminList').innerHTML='<div class="error">'+esc(e.message)+'</div>'}}
async function approve(id){const t=get('myschool_admin_token');const r=await fetch(API+'/api/admin/applications/'+id+'/approve',{method:'POST',headers:{Authorization:'Bearer '+t}});const d=await r.json();if(!r.ok)return alert(d.error||'Xatolik');alert('Tasdiqlandi. Student ID: '+d.studentId);adminPanel()}
async function rejectApp(id){const reason=prompt('Rad etish sababi:','Ma’lumotlar rasmiy ro‘yxat bilan tasdiqlanmadi.');if(reason===null)return;const t=get('myschool_admin_token');const r=await fetch(API+'/api/admin/applications/'+id+'/reject',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:JSON.stringify({reason})});const d=await r.json();if(!r.ok)return alert(d.error||'Xatolik');adminPanel()}
const student=get('myschool_student'),pendingId=get('myschool_pending_application');if(student)home();else if(pendingId)pending();else welcome();