const API='https://myschool-ai.onrender.com';
const app=document.getElementById('app');
const get=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch(e){return null}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const classes=['1-A','1-B','2-A','2-B','3-A','3-B','4-A','4-B','5-A','5-B','6-A','6-B','7-A','7-B','8-A','8-B','9-A','9-B','10-A','10-B','11-A','11-B'];

function welcome(){app.innerHTML='<section class="screen"><div class="panel center"><div class="cap">🎓</div><div class="brand">STEM SCHOOL</div><div class="divider"></div><div class="welcome-sub">Maktab tizimi</div><button class="primary" onclick="register()">KIRISH</button></div></section>'}
function register(){app.innerHTML='<div class="wrap"><section class="card"><button class="back" onclick="welcome()">← Orqaga</button><h1 class="title">Ro\'yxatdan o\'tish</h1><p class="muted">Ma\'lumotlaringiz katta administrator tomonidan tekshiriladi.</p><form id="reg"><div class="field"><label>Ism</label><input id="firstName" required maxlength="60"></div><div class="field"><label>Familiya</label><input id="lastName" required maxlength="60"></div><div class="field"><label>Sinf</label><select id="className" required><option value="">Sinfni tanlang</option>'+classes.map(x=>'<option>'+x+'</option>').join('')+'</select></div><div class="field"><label>Maktab kodi (agar berilgan bo\'lsa)</label><input id="schoolCode" maxlength="40"></div><button class="btn">Ariza yuborish</button><div id="formMsg"></div></form></section></div>';document.getElementById('reg').onsubmit=submitRegistration}
async function submitRegistration(e){e.preventDefault();const msg=document.getElementById('formMsg');msg.textContent='Yuborilmoqda...';try{const r=await fetch(API+'/api/students/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firstName:firstName.value,lastName:lastName.value,className:className.value,schoolCode:schoolCode.value})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Xatolik');save('myschool_pending_application',d.applicationId);pending()}catch(x){msg.className='error';msg.textContent=x.message}}
function pending(){app.innerHTML='<div class="wrap"><section class="card center"><div class="logo">⏳</div><h1 class="title">Arizangiz qabul qilindi</h1><p class="muted">Ma\'lumotlaringiz katta administrator tomonidan tekshirilmoqda.</p><div id="pendingStatus" class="status">Arizangiz tekshirilmoqda...</div><button class="btn secondary" onclick="checkStatus()">Holatni tekshirish</button></section></div>';checkStatus();window.poll=setInterval(checkStatus,10000)}
async function checkStatus(){const id=get('myschool_pending_application');if(!id)return;try{const r=await fetch(API+'/api/students/status/'+encodeURIComponent(id));const d=await r.json();const box=document.getElementById('pendingStatus');if(!box)return;if(d.status==='approved'){clearInterval(window.poll);save('myschool_student',{studentId:d.studentId,firstName:d.firstName,lastName:d.lastName,className:d.className});localStorage.removeItem('myschool_pending_application');box.innerHTML='<div class="success"><b>Tasdiqlandi!</b><br>Student ID: <strong>'+esc(d.studentId)+'</strong></div>';setTimeout(home,1500)}else if(d.status==='rejected'){clearInterval(window.poll);box.innerHTML='<div class="error"><b>Ariza rad etildi.</b><br>'+esc(d.rejectionReason)+'</div>'}else box.textContent='Arizangiz hali tekshirilmoqda...'}catch(e){const box=document.getElementById('pendingStatus');if(box)box.textContent='Server bilan bog‘lanishda xatolik.'}}

function login(){register()}
async function studentLogin(e){e.preventDefault();const msg=document.getElementById('loginMsg');msg.textContent='Tekshirilmoqda...';try{const r=await fetch(API+'/api/students/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studentId:studentIdInput.value})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Kirishda xatolik.');save('myschool_student',d.student);save('myschool_student_token',d.token);home()}catch(x){msg.className='error';msg.textContent=x.message}}

const schedule=[['Dushanba','08:00','Matematika','1-xona'],['Dushanba','08:50','Ona tili','2-xona'],['Seshanba','08:00','Ingliz tili','3-xona'],['Seshanba','08:50','Fizika','4-xona'],['Chorshanba','08:00','Informatika','5-xona'],['Chorshanba','08:50','Tarix','6-xona'],['Payshanba','08:00','Biologiya','7-xona'],['Payshanba','08:50','Geografiya','8-xona'],['Juma','08:00','Matematika','1-xona'],['Juma','08:50','Jismoniy tarbiya','Sport zal'],['Shanba','08:00','Adabiyot','2-xona']];
const subjectList=['Matematika','Ona tili','Adabiyot','Ingliz tili','Rus tili','Tarix','Geografiya','Biologiya','Fizika','Kimyo','Informatika','Jismoniy tarbiya'];

function home(){const s=get('myschool_student');if(!s)return welcome();app.innerHTML='<section class="screen"><div class="panel menu-card"><div class="menu-head"><div class="cap" style="opacity:1;animation:none;font-size:45px">🎓</div><h1>STEM SCHOOL</h1><div class="student">'+esc(s.firstName)+' '+esc(s.lastName)+' · <b>'+esc(s.className)+'</b><br>Student ID: <b>'+esc(s.studentId)+'</b></div></div><div class="grid"><button class="tile" onclick="showSchedule()"><span class="icon">📅</span><strong>JADVAL</strong></button><button class="tile" onclick="showSubjects()"><span class="icon">📖</span><strong>FANLAR</strong></button><button class="tile disabled" onclick="soon(event)"><span class="icon">🎯</span><strong>CAREER</strong></button><button class="tile disabled" onclick="soon(event)"><span class="icon">📢</span><strong>E’LON</strong></button><button class="tile disabled" onclick="soon(event)"><span class="icon">📚</span><strong>KITOBXONA</strong></button><button class="tile disabled" onclick="soon(event)"><span class="icon">❓</span><strong>INFO</strong></button></div><button class="wide disabled" onclick="soon(event)"><span class="icon">🤖</span><strong>AI YORDAMCHI</strong></button></div></section>'}
function soon(e){e.preventDefault();alert('Bu bo‘lim hozircha ishlamaydi. Keyingi bosqichda ulanadi.')}
function showSchedule(){
const s=get('myschool_student');const c=s?.className||'';
const defaultDays={Dushanba:['Matematika','Ingliz tili','Ona tili','Fizika','Informatika','Tarix','Biologiya','Adabiyot'],Seshanba:['Ona tili','Matematika','Fizika','Ingliz tili','Geografiya','Kimyo','Informatika','Jismoniy tarbiya'],Chorshanba:['Ingliz tili','Matematika','Tarix','Biologiya','Ona tili','Fizika','Geografiya','Informatika'],Payshanba:['Matematika','Adabiyot','Ingliz tili','Kimyo','Tarix','Biologiya','Ona tili','Jismoniy tarbiya'],Juma:['Fizika','Matematika','Informatika','Ingliz tili','Geografiya','Ona tili','Tarix','Adabiyot']};
const scheduleByGrade={1:{Dushanba:['Matematika','Ona tili','Ingliz tili','Informatika','Tabiiy fan','Tarbiya','Jismoniy tarbiya','Rasm'],Seshanba:['Ona tili','Matematika','Informatika','Ingliz tili','Tabiiy fan','Tarbiya','Rasm','Jismoniy tarbiya'],Chorshanba:['Matematika','Ingliz tili','Ona tili','Tabiiy fan','Informatika','Rasm','Tarbiya','Jismoniy tarbiya'],Payshanba:['Ingliz tili','Matematika','Ona tili','Informatika','Tabiiy fan','Rasm','Jismoniy tarbiya','Tarbiya'],Juma:['Matematika','Ona tili','Ingliz tili','Tabiiy fan','Informatika','Tarbiya','Rasm','Jismoniy tarbiya']}};
const n=parseInt(c,10)||8;const days=scheduleByGrade[n]||defaultDays;let cur=510,times=[];for(let i=1;i<=8;i++){let st=cur,en=cur+45;times.push([st,en]);cur=en;if(n<=4){if(i===3||i===7)cur+=45;else if(i<8)cur+=5}else{if(i===4||i===8)cur+=45;else if(i<8)cur+=5}}
const f=m=>String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');
app.innerHTML='<div class="wrap"><section class="card admin"><button class="back" onclick="home()">← Orqaga</button><h1 class="title">📅 Jadval</h1><p class="muted"><b>'+esc(c)+'</b> sinfi uchun haftalik jadval</p><div id="days" style="display:flex;gap:8px;overflow-x:auto;padding:8px 0 14px;"></div><div id="list"></div></section></div>';
const tabs=document.getElementById('days'),list=document.getElementById('list'),names=Object.keys(days);
tabs.innerHTML=names.map((d,i)=>'<button class="day-tab'+(i?'':' is-active')+'" data-day="'+d+'" type="button">'+d+'</button>').join('');
function render(d){tabs.querySelectorAll('.day-tab').forEach(x=>x.classList.remove('is-active'));tabs.querySelector('[data-day="'+d+'"]').classList.add('is-active');let h='<div class="schedule-table"><div class="schedule-table__head"><span>Fan</span><span style="text-align:right">Vaqt</span></div>';days[d].forEach((sub,i)=>{h+='<div class="schedule-row"><span class="schedule-row__subject">'+(i+1)+'. '+esc(sub)+'</span><span class="schedule-row__time">'+f(times[i][0])+'–'+f(times[i][1])+'</span></div>';if((n<=4&&i===2)||(n>=5&&i===3))h+='<div class="schedule-break"><span class="schedule-break__name">🍽️ ABET</span><span class="schedule-break__time">'+f(times[i][1])+'–'+f(times[i][1]+45)+'</span></div>';if((n<=4&&i===6)||(n>=5&&i===7))h+='<div class="schedule-break"><span class="schedule-break__name">🥪 PO‘LDNIK</span><span class="schedule-break__time">'+f(times[i][1])+'–'+f(times[i][1]+45)+'</span></div>'});list.innerHTML=h+'</div>'}
tabs.querySelectorAll('.day-tab').forEach(x=>x.onclick=()=>render(x.dataset.day));render(names[0])}
function showSubjects(){const s=get('myschool_student');app.innerHTML='<div class="wrap"><section class="card admin"><button class="back" onclick="home()">← Orqaga</button><h1 class="title">📚 Fanlar</h1><p class="muted"><b>'+esc(s?.className||'')+'</b> sinfi uchun fanlar</p><button class="btn" onclick="lessons()">📖 Darslar</button><button class="btn secondary" onclick="tests()">🧪 Testlar</button><button class="btn secondary" onclick="results()">📊 Natijalar</button></section></div>'}
function lessons(){app.innerHTML='<div class="wrap"><section class="card admin"><button class="back" onclick="showSubjects()">← Fanlarga qaytish</button><h1 class="title">📖 Darslar</h1><p class="muted">Fanni tanlang.</p>'+subjectList.map(x=>'<button class="btn secondary" onclick="lessonTopic(\''+x+'\')">'+x+'</button>').join('')+'</section></div>'}
function lessonTopic(subject){app.innerHTML='<div class="wrap"><section class="card"><button class="back" onclick="lessons()">← Darslarga qaytish</button><h1 class="title">'+esc(subject)+'</h1><p class="muted">Bu fan uchun mavzular, batafsil tushuntirishlar, formulalar, misollar va ko‘p uchraydigan xatolar keyingi bosqichda katta administrator tomonidan qo‘shiladi.</p><div class="status">📚 Mavzular tayyorlanmoqda.</div></section></div>'}
function tests(){app.innerHTML='<div class="wrap"><section class="card"><button class="back" onclick="showSubjects()">← Fanlarga qaytish</button><h1 class="title">🧪 Testlar</h1><p class="muted">Darajani tanlash keyingi bosqichda ulanadi.</p><button class="btn">Oson</button><button class="btn secondary">O‘rta</button><button class="btn secondary">Qiyin</button></section></div>'}
function results(){app.innerHTML='<div class="wrap"><section class="card"><button class="back" onclick="showSubjects()">← Fanlarga qaytish</button><h1 class="title">📊 Natijalar</h1><p class="muted">Testlar tarixi, eng yuqori natija, urinishlar, foiz, o‘rtacha natija va o‘sish grafigi keyingi bosqichda ulanadi.</p><div class="status">Hozircha natijalar mavjud emas.</div></section></div>'}

function adminLogin(){app.innerHTML='<div class="wrap"><section class="card"><button class="back" onclick="welcome()">← Orqaga</button><h1 class="title">Katta administrator</h1><div class="field"><label>Login</label><input id="au"></div><div class="field"><label>Parol</label><input id="ap" type="password"></div><button class="btn" onclick="doAdminLogin()">Kirish</button><div id="adminMsg"></div></section></div>'}
async function doAdminLogin(){const msg=document.getElementById('adminMsg');try{const r=await fetch(API+'/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:au.value,password:ap.value})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Xatolik');save('myschool_admin_token',d.token);adminPanel()}catch(e){msg.className='error';msg.textContent=e.message}}
async function adminPanel(){const token=get('myschool_admin_token');if(!token)return adminLogin();app.innerHTML='<div class="wrap"><section class="card admin"><h1 class="title">Katta administrator</h1><p class="muted">🔔 Yangi o‘quvchi arizalari</p><div id="adminList">Yuklanmoqda...</div><button class="btn secondary" onclick="adminPanel()">Yangilash</button><button class="btn danger" onclick="localStorage.removeItem(\'myschool_admin_token\');welcome()">Chiqish</button></section></div>';try{const r=await fetch(API+'/api/admin/applications',{headers:{Authorization:'Bearer '+token}});if(r.status===401)throw new Error('Sessiya tugagan.');const d=await r.json(),list=document.getElementById('adminList');if(!d.items.length){list.innerHTML='<div class="status">Hozircha yangi ariza yo‘q.</div>';return}list.innerHTML=d.items.map(a=>'<article class="app-item"><span class="badge">Yangi ariza</span><h3>'+esc(a.firstName)+' '+esc(a.lastName)+'</h3><p class="muted">Sinf: <b>'+esc(a.className)+'</b><br>Maktab kodi: '+esc(a.schoolCode||'kiritilmagan')+'</p><div class="row"><button class="btn" onclick="approve(\''+a._id+'\')">Tasdiqlash</button><button class="btn danger" onclick="rejectApp(\''+a._id+'\')">Rad etish</button></div></article>').join('')}catch(e){document.getElementById('adminList').innerHTML='<div class="error">'+esc(e.message)+'</div>'}}
async function approve(id){const t=get('myschool_admin_token');const r=await fetch(API+'/api/admin/applications/'+id+'/approve',{method:'POST',headers:{Authorization:'Bearer '+t}});const d=await r.json();if(!r.ok)return alert(d.error||'Xatolik');alert('Tasdiqlandi. Student ID: '+d.studentId);adminPanel()}
async function rejectApp(id){const reason=prompt('Rad etish sababi:','Ma’lumotlar rasmiy ro‘yxat bilan tasdiqlanmadi.');if(reason===null)return;const t=get('myschool_admin_token');const r=await fetch(API+'/api/admin/applications/'+id+'/reject',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:JSON.stringify({reason})});const d=await r.json();if(!r.ok)return alert(d.error||'Xatolik');adminPanel()}

const student=get('myschool_student'),pendingId=get('myschool_pending_application');
if(location.pathname==='/admin'||location.pathname==='/admin/')adminLogin();
else if(student)home();
else if(pendingId)pending();
else welcome();