const express=require('express');
const cors=require('cors');
const mongoose=require('mongoose');
const jwt=require('jsonwebtoken');
const app=express(); app.use(cors()); app.use(express.json({limit:'1mb'}));
const PORT=process.env.PORT||10000;
const JWT_SECRET=process.env.JWT_SECRET||process.env.ADMIN_SECRET||'change-this-secret';
const ADMIN_USERNAME=process.env.ADMIN_USERNAME||'admin';
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'change-this-password';
const schema=new mongoose.Schema({firstName:{type:String,required:true,trim:true},lastName:{type:String,required:true,trim:true},className:{type:String,required:true,trim:true},schoolCode:{type:String,default:'',trim:true},status:{type:String,enum:['pending','approved','rejected'],default:'pending'},rejectionReason:{type:String,default:''},studentId:{type:String,default:''},isBlocked:{type:Boolean,default:false},createdAt:{type:Date,default:Date.now},reviewedAt:{type:Date,default:null}});
const Application=mongoose.model('Application',schema);
const contentSchema=new mongoose.Schema({kind:{type:String,enum:['announcements','library','social'],required:true},title:{type:String,required:true,trim:true,maxlength:140},body:{type:String,default:'',maxlength:4000},url:{type:String,default:''},createdAt:{type:Date,default:Date.now}});
const SchoolContent=mongoose.model('SchoolContent',contentSchema);
const SchoolData=mongoose.model('SchoolData',new mongoose.Schema({
 kind:{type:String,required:true,index:true},
 data:{type:mongoose.Schema.Types.Mixed,default:{}},
 createdAt:{type:Date,default:Date.now},
 updatedAt:{type:Date,default:Date.now}
}));

function auth(req,res,next){try{const h=req.headers.authorization||'';const t=h.split(' ')[1]||'';const p=jwt.verify(t,JWT_SECRET);if(p.role!=='big-admin')throw new Error();next()}catch(e){res.status(401).json({error:'Admin authentication required'})}}
async function newId(){let id;do{id=String(Math.floor(100000+Math.random()*900000))}while(await Application.exists({studentId:id}));return id}
app.get('/api/health',(q,r)=>r.json({ok:true,service:'myschool'}));
app.post('/api/students/register',async(req,res)=>{try{const firstName=String(req.body.firstName||'').trim(),lastName=String(req.body.lastName||'').trim(),className=String(req.body.className||'').trim().toUpperCase(),schoolCode=String(req.body.schoolCode||'').trim();if(!firstName||!lastName||!className)return res.status(400).json({error:'Ism, familiya va sinf majburiy.'});const a=await Application.create({firstName,lastName,className,schoolCode});res.status(201).json({ok:true,applicationId:String(a._id),status:a.status})}catch(e){console.error(e);res.status(500).json({error:'Arizani yuborishda xatolik.'})}});
app.get('/api/students/status/:id',async(req,res)=>{try{const a=await Application.findById(req.params.id).lean();if(!a)return res.status(404).json({error:'Ariza topilmadi.'});res.json({status:a.status,studentId:a.studentId||'',rejectionReason:a.rejectionReason||'',firstName:a.firstName,lastName:a.lastName,className:a.className})}catch(e){res.status(400).json({error:'Noto‘g‘ri ariza ID.'})}});
app.post('/api/students/login',async(req,res)=>{try{const studentId=String(req.body.studentId||'').trim();if(!/^\d{6}$/.test(studentId))return res.status(400).json({error:'Student ID 6 xonali raqam bo‘lishi kerak.'});const a=await Application.findOne({studentId,status:'approved'}).lean();if(!a)return res.status(401).json({error:'Student ID topilmadi yoki hali tasdiqlanmagan.'});if(a.isBlocked)return res.status(403).json({error:'Hisobingiz administrator tomonidan bloklangan.'});const token=jwt.sign({role:'student',studentId:a.studentId},JWT_SECRET,{expiresIn:'30d'});res.json({ok:true,token,student:{studentId:a.studentId,firstName:a.firstName,lastName:a.lastName,className:a.className}})}catch(e){console.error(e);res.status(500).json({error:'Kirishda xatolik.'})}});
app.post('/api/admin/login',(req,res)=>{if(String(req.body.username||'')!==ADMIN_USERNAME||String(req.body.password||'')!==ADMIN_PASSWORD)return res.status(401).json({error:'Login yoki parol noto‘g‘ri.'});res.json({ok:true,token:jwt.sign({role:'big-admin',username:ADMIN_USERNAME},JWT_SECRET,{expiresIn:'12h'})})});
app.get('/api/admin/applications',auth,async(q,res)=>res.json({items:await Application.find({status:'pending'}).sort({createdAt:-1}).lean()}));
app.get('/api/admin/students',auth,async(req,res)=>{try{const search=String(req.query.search||'').trim().toLowerCase();const items=await Application.find({status:'approved'}).sort({createdAt:-1}).select('firstName lastName className studentId isBlocked createdAt').lean();const matched=search?items.filter(a=>[a.studentId,a.firstName,a.lastName,a.className].some(v=>String(v||'').toLowerCase().includes(search))):items;res.json({items:matched})}catch(e){res.status(500).json({error:'O‘quvchilarni yuklashda xatolik.'})}});
app.patch('/api/admin/students/:id',auth,async(req,res)=>{try{const a=await Application.findOne({_id:req.params.id,status:'approved'});if(!a)return res.status(404).json({error:'O‘quvchi topilmadi.'});if(req.body.firstName!==undefined)a.firstName=String(req.body.firstName).trim();if(req.body.lastName!==undefined)a.lastName=String(req.body.lastName).trim();if(req.body.className!==undefined)a.className=String(req.body.className).trim().toUpperCase();if(req.body.isBlocked!==undefined)a.isBlocked=Boolean(req.body.isBlocked);if(!a.firstName||!a.lastName||!a.className)return res.status(400).json({error:'Ism, familiya va sinf bo‘sh bo‘lmasin.'});await a.save();res.json({ok:true})}catch(e){res.status(400).json({error:'O‘quvchini yangilashda xatolik.'})}});
app.delete('/api/admin/students/:id',auth,async(req,res)=>{try{const a=await Application.findOneAndDelete({_id:req.params.id,status:'approved'});if(!a)return res.status(404).json({error:'O‘quvchi topilmadi.'});res.json({ok:true})}catch(e){res.status(500).json({error:'O‘quvchini o‘chirishda xatolik.'})}});
app.get('/api/public/content/:kind',async(req,res)=>{try{const kind=String(req.params.kind||'');if(!['announcements','library','social'].includes(kind))return res.status(400).json({error:'Noto‘g‘ri bo‘lim.'});res.json({items:await SchoolContent.find({kind}).sort({createdAt:-1}).lean()})}catch(e){res.status(500).json({error:'Ma’lumotlarni yuklashda xatolik.'})}});
app.get('/api/admin/content',auth,async(req,res)=>{try{const kind=String(req.query.kind||'');if(!['announcements','library','social'].includes(kind))return res.status(400).json({error:'Noto‘g‘ri bo‘lim.'});res.json({items:await SchoolContent.find({kind}).sort({createdAt:-1}).lean()})}catch(e){res.status(500).json({error:'Ma’lumotlarni yuklashda xatolik.'})}});
app.post('/api/admin/content',auth,async(req,res)=>{try{const kind=String(req.body.kind||''),title=String(req.body.title||'').trim(),body=String(req.body.body||'').trim(),url=String(req.body.url||'').trim();if(!['announcements','library','social'].includes(kind)||!title)return res.status(400).json({error:'Bo‘lim va nom majburiy.'});if(url&&!/^https?:\/\//i.test(url))return res.status(400).json({error:'Havola http:// yoki https:// bilan boshlansin.'});const item=await SchoolContent.create({kind,title,body,url});res.status(201).json({ok:true,item})}catch(e){res.status(400).json({error:'Ma’lumotni saqlashda xatolik.'})}});
app.delete('/api/admin/content/:id',auth,async(req,res)=>{try{const item=await SchoolContent.findByIdAndDelete(req.params.id);if(!item)return res.status(404).json({error:'Yozuv topilmadi.'});res.json({ok:true})}catch(e){res.status(400).json({error:'Yozuvni o‘chirishda xatolik.'})}});
app.get('/api/data/:kind',async(req,res)=>{try{const kind=String(req.params.kind||'');const items=await SchoolData.find({kind}).sort({createdAt:-1}).lean();res.json({items})}catch(e){res.status(500).json({error:'Ma\'lumotlarni yuklashda xatolik.'})}});
app.get('/api/admin/data/:kind',auth,async(req,res)=>{try{const kind=String(req.params.kind||'');const items=await SchoolData.find({kind}).sort({updatedAt:-1}).lean();res.json({items})}catch(e){res.status(500).json({error:'Ma\'lumotlarni yuklashda xatolik.'})}});
app.post('/api/admin/data/:kind',auth,async(req,res)=>{try{const kind=String(req.params.kind||'');const data=req.body||{};const item=await SchoolData.create({kind,data,updatedAt:new Date()});res.status(201).json({ok:true,item})}catch(e){console.error(e);res.status(400).json({error:'Ma\'lumotni saqlashda xatolik.'})}});
app.put('/api/admin/data/:id',auth,async(req,res)=>{try{const item=await SchoolData.findByIdAndUpdate(req.params.id,{data:req.body||{},updatedAt:new Date()},{new:true});if(!item)return res.status(404).json({error:'Yozuv topilmadi.'});res.json({ok:true,item})}catch(e){res.status(400).json({error:'Ma\'lumotni yangilashda xatolik.'})}});
app.delete('/api/admin/data/:id',auth,async(req,res)=>{try{const item=await SchoolData.findByIdAndDelete(req.params.id);if(!item)return res.status(404).json({error:'Yozuv topilmadi.'});res.json({ok:true})}catch(e){res.status(400).json({error:'Yozuvni o\'chirishda xatolik.'})}});
app.post('/api/students/results',async(req,res)=>{try{const data=req.body||{};if(!data.studentId||!data.subject)return res.status(400).json({error:'Natija ma\'lumotlari to\'liq emas.'});const item=await SchoolData.create({kind:'results',data,updatedAt:new Date()});res.status(201).json({ok:true,item})}catch(e){res.status(400).json({error:'Natijani saqlashda xatolik.'})}});
app.post('/api/admin/applications/:id/approve',auth,async(req,res)=>{const a=await Application.findById(req.params.id);if(!a)return res.status(404).json({error:'Ariza topilmadi.'});if(a.status!=='pending')return res.status(400).json({error:'Ariza allaqachon ko‘rib chiqilgan.'});a.status='approved';a.studentId=await newId();a.reviewedAt=new Date();await a.save();res.json({ok:true,studentId:a.studentId})});
app.post('/api/admin/applications/:id/reject',auth,async(req,res)=>{const a=await Application.findById(req.params.id);if(!a)return res.status(404).json({error:'Ariza topilmadi.'});a.status='rejected';a.rejectionReason=String(req.body.reason||'Ma’lumotlar tasdiqlanmadi.').trim();a.reviewedAt=new Date();await a.save();res.json({ok:true})});
async function start(){if(process.env.MONGODB_URI){await mongoose.connect(process.env.MONGODB_URI);console.log('MongoDB connected')}else console.warn('MONGODB_URI is not set');app.listen(PORT,()=>console.log('MySchool API listening on '+PORT))}
start().catch(e=>{console.error(e);process.exit(1)})