const express=require('express');
const mongoose=require('mongoose');
const cors=require('cors');
const jwt=require('jsonwebtoken');
const crypto=require('crypto');
const app=express();
app.use(cors());
app.use(express.json({limit:'3mb'}));
const PORT=process.env.PORT||10000;
const MONGO_URI=process.env.MONGODB_URI||process.env.MONGO_URI;
const JWT_SECRET=process.env.JWT_SECRET||'change-this-secret';
const ADMIN_USERNAME=process.env.ADMIN_USERNAME||'admin';
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'change-this-password';
const School=mongoose.model('School',new mongoose.Schema({name:{type:String,required:true,trim:true},code:{type:String,required:true,unique:true,uppercase:true,trim:true},slug:{type:String,required:true,unique:true,lowercase:true,trim:true},isActive:{type:Boolean,default:true},createdAt:{type:Date,default:Date.now}}));
const Application=mongoose.model('Application',new mongoose.Schema({schoolId:{type:mongoose.Schema.Types.ObjectId,ref:'School',required:true,index:true},firstName:{type:String,required:true,trim:true},lastName:{type:String,required:true,trim:true},className:{type:String,required:true,trim:true},photoData:{type:String,default:''},status:{type:String,enum:['pending','approved','rejected'],default:'pending',index:true},rejectionReason:{type:String,default:''},studentId:{type:String,default:'',index:true},isBlocked:{type:Boolean,default:false},createdAt:{type:Date,default:Date.now},reviewedAt:{type:Date,default:null}}));
const Student=mongoose.model('Student',new mongoose.Schema({schoolId:{type:mongoose.Schema.Types.ObjectId,ref:'School',required:true,index:true},studentId:{type:String,required:true,unique:true,index:true},firstName:{type:String,required:true},lastName:{type:String,required:true},className:{type:String,required:true},photoData:{type:String,default:''},isBlocked:{type:Boolean,default:false},createdAt:{type:Date,default:Date.now}}));
const Staff=mongoose.model('Staff',new mongoose.Schema({schoolId:{type:mongoose.Schema.Types.ObjectId,ref:'School',required:true,index:true},fullName:{type:String,required:true},username:{type:String,required:true,unique:true,index:true},passwordHash:{type:String,required:true},passwordSalt:{type:String,required:true},role:{type:String,enum:['teacher','admin','director'],required:true},subject:{type:String,default:''},isBlocked:{type:Boolean,default:false},createdAt:{type:Date,default:Date.now}}));
const Announcement=mongoose.model('Announcement',new mongoose.Schema({schoolId:{type:mongoose.Schema.Types.ObjectId,ref:'School',required:true,index:true},title:{type:String,required:true},text:{type:String,required:true},createdAt:{type:Date,default:Date.now}}));
const LibraryBook=mongoose.model('LibraryBook',new mongoose.Schema({schoolId:{type:mongoose.Schema.Types.ObjectId,ref:'School',required:true,index:true},title:{type:String,required:true},author:{type:String,default:''},description:{type:String,default:''},createdAt:{type:Date,default:Date.now}}));
const Subject=mongoose.model('Subject',new mongoose.Schema({schoolId:{type:mongoose.Schema.Types.ObjectId,ref:'School',required:true,index:true},name:{type:String,required:true},teacher:{type:String,default:''},description:{type:String,default:''},createdAt:{type:Date,default:Date.now}}));
const ScheduleEntry=mongoose.model('ScheduleEntry',new mongoose.Schema({schoolId:{type:mongoose.Schema.Types.ObjectId,ref:'School',required:true,index:true},className:{type:String,required:true},day:{type:Number,required:true},lesson:{type:Number,required:true},subject:{type:String,required:true},teacher:{type:String,default:''},room:{type:String,default:''},createdAt:{type:Date,default:Date.now}}));
const ReadingTask=mongoose.model('ReadingTask',new mongoose.Schema({schoolId:{type:mongoose.Schema.Types.ObjectId,ref:'School',required:true,index:true},title:{type:String,required:true},book:{type:String,default:''},pages:{type:Number,default:0},description:{type:String,default:''},createdAt:{type:Date,default:Date.now}}));
const SupportInfo=mongoose.model('SupportInfo',new mongoose.Schema({schoolId:{type:mongoose.Schema.Types.ObjectId,ref:'School',required:true,unique:true},text:{type:String,default:'Savollar bo‘lsa, maktab administratoriga murojaat qiling.'},updatedAt:{type:Date,default:Date.now}}));
const Test=mongoose.model('Test',new mongoose.Schema({schoolId:{type:mongoose.Schema.Types.ObjectId,ref:'School',required:true,index:true},title:{type:String,required:true},subject:{type:String,default:''},className:{type:String,default:''},duration:{type:Number,default:45},questionsText:{type:String,default:''},createdAt:{type:Date,default:Date.now}}));
const Result=mongoose.model('Result',new mongoose.Schema({schoolId:{type:mongoose.Schema.Types.ObjectId,ref:'School',required:true,index:true},studentId:{type:String,required:true,index:true},testId:{type:mongoose.Schema.Types.ObjectId,ref:'Test',required:false},testTitle:{type:String,default:''},score:{type:Number,default:0},maxScore:{type:Number,default:0},grade:{type:String,default:''},note:{type:String,default:''},createdAt:{type:Date,default:Date.now}}));
const MediaItem=mongoose.model('MediaItem',new mongoose.Schema({schoolId:{type:mongoose.Schema.Types.ObjectId,ref:'School',required:true,index:true},title:{type:String,required:true},type:{type:String,enum:['banner','image'],default:'banner'},url:{type:String,default:''},description:{type:String,default:''},createdAt:{type:Date,default:Date.now}}));
const TelegramConfig=mongoose.model('TelegramConfig',new mongoose.Schema({schoolId:{type:mongoose.Schema.Types.ObjectId,ref:'School',required:true,unique:true},botUsername:{type:String,default:''},miniAppUrl:{type:String,default:''},channelUsername:{type:String,default:''},webhookUrl:{type:String,default:''},updatedAt:{type:Date,default:Date.now}}));
const Meta=mongoose.model('Meta',new mongoose.Schema({key:{type:String,unique:true},value:String}));
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return {salt,hash:crypto.scryptSync(String(password),salt,64).toString('hex')}}
function verifyPassword(password,salt,hash){const a=Buffer.from(hashPassword(password,salt).hash,'hex'),b=Buffer.from(hash,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function token(payload){return jwt.sign(payload,JWT_SECRET,{expiresIn:'30d'})}
function guard(role){return (req,res,next)=>{try{const t=(req.headers.authorization||'').split(' ')[1];const p=jwt.verify(t,JWT_SECRET);if(p.role!==role)throw new Error();req.auth=p;next()}catch(e){res.status(401).json({error:'Avtorizatsiya talab qilinadi.'})}}}
const admin=guard('big-admin'),studentGuard=guard('student'),staffGuard=guard('staff');
function validClass(v){return /^(?:[1-9]|10|11)-[ABGV]$/.test(String(v||'').toUpperCase())}
async function nextStudentId(){let id;do{id=String(Math.floor(100000+Math.random()*900000))}while(await Student.exists({studentId:id}));return id}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'MySchool',database:mongoose.connection.name||null}));
app.post('/api/students/register',async(req,res)=>{try{const firstName=String(req.body.firstName||'').trim(),lastName=String(req.body.lastName||'').trim(),className=String(req.body.className||'').trim().toUpperCase(),schoolCode=String(req.body.schoolCode||'').trim().toUpperCase();if(firstName.length<2||lastName.length<2||!validClass(className))return res.status(400).json({error:'Maʼlumotlarni to‘g‘ri kiriting.'});const school=await School.findOne({code:schoolCode||'STEM',isActive:true});if(!school)return res.status(404).json({error:'Maktab kodi topilmadi.'});const application=await Application.create({schoolId:school._id,firstName,lastName,className,photoData:String(req.body.photoData||'')});res.status(201).json({ok:true,applicationId:String(application._id),status:'pending'})}catch(e){console.error(e);res.status(500).json({error:'Ariza yuborishda xatolik.'})}});
app.get('/api/students/application/:id',async(req,res)=>{try{const a=await Application.findById(req.params.id).populate('schoolId','name code').lean();if(!a)return res.status(404).json({error:'Ariza topilmadi.'});res.json({ok:true,status:a.status,firstName:a.firstName,lastName:a.lastName,className:a.className,studentId:a.studentId,rejectionReason:a.rejectionReason})}catch(e){res.status(400).json({error:'Arizani tekshirishda xatolik.'})}});
app.post('/api/students/login',async(req,res)=>{try{const id=String(req.body.studentId||'').trim();if(!/^\d{6}$/.test(id))return res.status(400).json({error:'Student ID 6 xonali bo‘lishi kerak.'});const s=await Student.findOne({studentId:id}).lean();if(!s)return res.status(404).json({error:'Student ID topilmadi.'});if(s.isBlocked)return res.status(403).json({error:'Profil bloklangan.'});res.json({ok:true,token:token({role:'student',studentId:s.studentId,schoolId:String(s.schoolId)}),student:{studentId:s.studentId,firstName:s.firstName,lastName:s.lastName,className:s.className,photoData:s.photoData}})}catch(e){res.status(500).json({error:'Kirishda xatolik.'})}});
app.get('/api/student/me',studentGuard,async(req,res)=>{const s=await Student.findOne({studentId:req.auth.studentId}).populate('schoolId','name code').lean();if(!s)return res.status(404).json({error:'O‘quvchi topilmadi.'});res.json({ok:true,student:s})});
app.post('/api/admin/login',async(req,res)=>{if(String(req.body.username||'')!==ADMIN_USERNAME||String(req.body.password||'')!==ADMIN_PASSWORD)return res.status(401).json({error:'Login yoki parol noto‘g‘ri.'});res.json({ok:true,token:token({role:'big-admin'}),admin:{username:ADMIN_USERNAME}})});
app.get('/api/admin/dashboard',admin,async(req,res)=>{const [pending,students,staff,schools]=await Promise.all([Application.countDocuments({status:'pending'}),Student.countDocuments(),Staff.countDocuments(),School.countDocuments({isActive:true})]);res.json({ok:true,pending,students,staff,schools})});
app.get('/api/admin/applications',admin,async(req,res)=>res.json({ok:true,items:await Application.find({status:'pending'}).populate('schoolId','name code').sort({createdAt:-1}).lean()}));
app.get('/api/admin/students',admin,async(req,res)=>res.json({ok:true,items:await Student.find().populate('schoolId','name code').sort({createdAt:-1}).lean()}));
app.post('/api/admin/applications/:id/approve',admin,async(req,res)=>{try{const a=await Application.findOne({_id:req.params.id,status:'pending'});if(!a)return res.status(404).json({error:'Ariza topilmadi.'});const studentId=await nextStudentId();const s=await Student.create({schoolId:a.schoolId,studentId,firstName:a.firstName,lastName:a.lastName,className:a.className,photoData:a.photoData});a.status='approved';a.studentId=studentId;a.reviewedAt=new Date();await a.save();res.json({ok:true,student:{studentId:s.studentId,firstName:s.firstName,lastName:s.lastName,className:s.className}})}catch(e){console.error(e);res.status(500).json({error:'Tasdiqlashda xatolik.'})}});
app.post('/api/admin/applications/:id/reject',admin,async(req,res)=>{const a=await Application.findOne({_id:req.params.id,status:'pending'});if(!a)return res.status(404).json({error:'Ariza topilmadi.'});a.status='rejected';a.rejectionReason=String(req.body.reason||'Ariza rad etildi.').trim();a.reviewedAt=new Date();await a.save();res.json({ok:true})});
app.delete('/api/admin/applications/:id',admin,async(req,res)=>{await Application.findByIdAndDelete(req.params.id);res.json({ok:true})});
app.patch('/api/admin/students/:id/block',admin,async(req,res)=>{const s=await Student.findById(req.params.id);if(!s)return res.status(404).json({error:'O‘quvchi topilmadi.'});s.isBlocked=Boolean(req.body.blocked);await s.save();res.json({ok:true,blocked:s.isBlocked})});
app.delete('/api/admin/students/:id',admin,async(req,res)=>{await Student.findByIdAndDelete(req.params.id);res.json({ok:true})});

// Student content
app.get('/api/student/announcements',studentGuard,async(req,res)=>res.json({ok:true,items:await Announcement.find({schoolId:req.auth.schoolId}).sort({createdAt:-1}).lean()}));
app.get('/api/student/books',studentGuard,async(req,res)=>res.json({ok:true,items:await LibraryBook.find({schoolId:req.auth.schoolId}).sort({createdAt:-1}).lean()}));
app.get('/api/student/subjects',studentGuard,async(req,res)=>res.json({ok:true,items:await Subject.find({schoolId:req.auth.schoolId}).sort({name:1}).lean()}));
app.get('/api/student/schedule',studentGuard,async(req,res)=>{const s=await Student.findOne({studentId:req.auth.studentId}).lean();res.json({ok:true,items:await ScheduleEntry.find({schoolId:req.auth.schoolId,className:s?.className||''}).sort({day:1,lesson:1}).lean()})});
app.get('/api/student/reading',studentGuard,async(req,res)=>res.json({ok:true,items:await ReadingTask.find({schoolId:req.auth.schoolId}).sort({createdAt:-1}).lean()}));
app.get('/api/student/support',studentGuard,async(req,res)=>{const x=await SupportInfo.findOne({schoolId:req.auth.schoolId}).lean();res.json({ok:true,item:x||{text:'Savollar bo‘lsa, maktab administratoriga murojaat qiling.'}})});

// Big Admin content CRUD
const adminCrud=(Model,path,label)=>{app.get('/api/admin/'+path,admin,async(req,res)=>res.json({ok:true,items:await Model.find().populate('schoolId','name code').sort({createdAt:-1}).lean()}));app.post('/api/admin/'+path,admin,async(req,res)=>{try{const school=await School.findOne({isActive:true});if(!school)return res.status(400).json({error:'Faol maktab yo‘q.'});const item=await Model.create({...req.body,schoolId:school._id});res.status(201).json({ok:true,item})}catch(e){res.status(400).json({error:label+' yaratilmadi.'})}});app.delete('/api/admin/'+path+'/:id',admin,async(req,res)=>{await Model.findByIdAndDelete(req.params.id);res.json({ok:true})})};
adminCrud(Announcement,'announcements','E’lon');
adminCrud(LibraryBook,'books','Kitob');
adminCrud(Subject,'subjects','Fan');
adminCrud(ScheduleEntry,'schedule','Jadval');
adminCrud(ReadingTask,'reading','Kitobxonlik');
adminCrud(Test,'tests','Test');
adminCrud(Result,'results','Natija');
adminCrud(MediaItem,'media','Media');
app.get('/api/admin/telegram',admin,async(req,res)=>{const school=await School.findOne({isActive:true});const item=school?await TelegramConfig.findOne({schoolId:school._id}).lean():null;res.json({ok:true,item:item||{}})});
app.put('/api/admin/telegram',admin,async(req,res)=>{const school=await School.findOne({isActive:true});if(!school)return res.status(400).json({error:'Faol maktab yo‘q.'});const item=await TelegramConfig.findOneAndUpdate({schoolId:school._id},{botUsername:String(req.body.botUsername||''),miniAppUrl:String(req.body.miniAppUrl||''),channelUsername:String(req.body.channelUsername||''),webhookUrl:String(req.body.webhookUrl||''),updatedAt:new Date()},{upsert:true,new:true,setDefaultsOnInsert:true});res.json({ok:true,item})});
app.get('/api/admin/support',admin,async(req,res)=>res.json({ok:true,item:await SupportInfo.findOne().lean()}));
app.put('/api/admin/support',admin,async(req,res)=>{const school=await School.findOne({isActive:true});const item=await SupportInfo.findOneAndUpdate({schoolId:school._id},{text:String(req.body.text||''),updatedAt:new Date()},{upsert:true,new:true,setDefaultsOnInsert:true});res.json({ok:true,item})});
app.get('/api/admin/schools',admin,async(req,res)=>res.json({ok:true,items:await School.find().sort({createdAt:-1}).lean()}));
app.post('/api/admin/schools',admin,async(req,res)=>{try{const name=String(req.body.name||'').trim(),code=String(req.body.code||'').trim().toUpperCase(),slug=String(req.body.slug||'').trim().toLowerCase();if(!name||!code||!slug)return res.status(400).json({error:'Maktab nomi, kodi va slug kerak.'});const s=await School.create({name,code,slug});res.status(201).json({ok:true,item:s})}catch(e){res.status(409).json({error:'Maktab kodi yoki slug band.'})}});
app.post('/api/staff/login',async(req,res)=>{const username=String(req.body.username||'').trim(),password=String(req.body.password||'');const s=await Staff.findOne({username}).lean();if(!s||s.isBlocked||!verifyPassword(password,s.passwordSalt,s.passwordHash))return res.status(401).json({error:'Login yoki parol noto‘g‘ri.'});res.json({ok:true,token:token({role:'staff',staffId:String(s._id),schoolId:String(s.schoolId)}),staff:{fullName:s.fullName,role:s.role,subject:s.subject}})});
app.get('/api/staff/me',staffGuard,async(req,res)=>{const s=await Staff.findById(req.auth.staffId).populate('schoolId','name code').lean();if(!s)return res.status(404).json({error:'Ishchi topilmadi.'});res.json({ok:true,staff:s})});
app.post('/api/admin/staff',admin,async(req,res)=>{try{const {fullName,username,password,role='teacher',subject=''}=req.body;if(!fullName||!username||!password)return res.status(400).json({error:'Barcha majburiy maydonlarni to‘ldiring.'});const school=await School.findOne({isActive:true});if(!school)return res.status(400).json({error:'Faol maktab yo‘q.'});const hp=hashPassword(password);const s=await Staff.create({schoolId:school._id,fullName:String(fullName).trim(),username:String(username).trim(),passwordHash:hp.hash,passwordSalt:hp.salt,role,subject:String(subject||'').trim()});res.status(201).json({ok:true,id:String(s._id)})}catch(e){res.status(409).json({error:'Ishchi yaratilmadi. Username band bo‘lishi mumkin.'})}});
app.get('/api/admin/staff',admin,async(req,res)=>res.json({ok:true,items:await Staff.find().populate('schoolId','name code').sort({createdAt:-1}).lean()}));
async function bootstrap(){if(!MONGO_URI)throw new Error('MONGODB_URI is missing');await mongoose.connect(MONGO_URI);if(process.env.RESET_DATABASE_ONCE==='true'&&!(await Meta.exists({key:'database-reset-2026-10-04'}))){await mongoose.connection.dropDatabase();await Meta.create({key:'database-reset-2026-10-04',value:'done'})}let school=await School.findOne({code:'STEM'});if(!school)school=await School.create({name:'STEM School',code:'STEM',slug:'stem-school'});if(!(await Staff.exists({username:'teacher'}))){const hp=hashPassword('teacher123');await Staff.create({schoolId:school._id,fullName:'Demo Teacher',username:'teacher',passwordHash:hp.hash,passwordSalt:hp.salt,role:'teacher',subject:'General'})}console.log('MySchool clean backend ready',{database:mongoose.connection.name});app.listen(PORT,'0.0.0.0',()=>console.log('MySchool API listening on '+PORT))}bootstrap().catch(e=>{console.error('BOOT ERROR',e);process.exit(1)});